name: basf_flutter_components_example
description: Demonstrates how to use the basf_flutter_components library.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  basf_flutter_components:
    # When depending on this package from a real application you should use:
    #   basf_flutter_components: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true